version: '3'
networks:
  commnet:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  node_1:
    image: "p2p-fl:latest"
    volumes:
      - ./demo:/home/demo
      - ./data/node-1:/home/work/p2plib/cmd/flat/data
      - ./data/node-1/keras-preload:/root/.keras/datasets
    ports:
      - "8080:5000"
    environment:
      - NODE_ID=1
      - GROUP_ID=1
      - SELF_IP=172.20.0.2
    networks:
      commnet:
        ipv4_address: 172.20.0.2
    restart: on-failure

  node_2:
    image: "p2p-fl:latest"
    volumes:
      - ./demo:/home/demo
      - ./data/node-2:/home/work/p2plib/cmd/flat/data
      - ./data/node-2/keras-preload:/root/.keras/datasets
    environment:
      - NODE_ID=2
      - GROUP_ID=1
      - SELF_IP=172.20.0.3
    networks:
      commnet:
        ipv4_address: 172.20.0.3
    restart: on-failure
    depends_on:
      - node_1

  node_3:
    image: "p2p-fl:latest"
    volumes:
      - ./demo:/home/demo
      - ./data/node-3:/home/work/p2plib/cmd/flat/data
      - ./data/node-3/keras-preload:/root/.keras/datasets
    environment:
      - NODE_ID=3
      - GROUP_ID=1
      - SELF_IP=172.20.0.4
    networks:
      commnet:
        ipv4_address: 172.20.0.4
    restart: on-failure
    depends_on:
      - node_2

  node_4:
    image: "p2p-fl:latest"
    volumes:
      - ./demo:/home/demo
      - ./data/node-4:/home/work/p2plib/cmd/flat/data
      - ./data/node-4/keras-preload:/root/.keras/datasets
    environment:
      - NODE_ID=4
      - GROUP_ID=1
      - SELF_IP=172.20.0.5
    networks:
      commnet:
        ipv4_address: 172.20.0.5
    restart: on-failure
    depends_on:
      - node_3

  node_5:
    image: "p2p-fl:latest"

    volumes:
      - ./demo:/home/demo
      - ./data/node-5:/home/work/p2plib/cmd/flat/data
      - ./data/node-5/keras-preload:/root/.keras/datasets
    environment:
      - NODE_ID=5
      - GROUP_ID=2
      - SELF_IP=172.20.0.6
    networks:
      commnet:
        ipv4_address: 172.20.0.6
    restart: on-failure
    depends_on:
      - node_4

  node_6:
    image: "p2p-fl:latest"

    volumes:
      - ./demo:/home/demo
      - ./data/node-6:/home/work/p2plib/cmd/flat/data
      - ./data/node-6/keras-preload:/root/.keras/datasets
    environment:
      - NODE_ID=6
      - GROUP_ID=2
      - SELF_IP=172.20.0.7
    networks:
      commnet:
        ipv4_address: 172.20.0.7
    restart: on-failure
    depends_on:
      - node_5
